// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFfFz8KfESc390R7T5BFwowgAsLLSiWg',
    appId: '1:627877852836:web:c1d977977a472fcd809831',
    messagingSenderId: '627877852836',
    projectId: 'wanderwave-faf5a',
    authDomain: 'wanderwave-faf5a.firebaseapp.com',
    storageBucket: 'wanderwave-faf5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1NFlwjVc9KT0YcReXE_hvA09adOuPm2k',
    appId: '1:627877852836:android:9b9511e0e3aa3d47809831',
    messagingSenderId: '627877852836',
    projectId: 'wanderwave-faf5a',
    storageBucket: 'wanderwave-faf5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCexbjtChbL3_KM1RtY0POQMQYZtXFHKaA',
    appId: '1:627877852836:ios:d277df96260cdeab809831',
    messagingSenderId: '627877852836',
    projectId: 'wanderwave-faf5a',
    storageBucket: 'wanderwave-faf5a.appspot.com',
    iosBundleId: 'com.example.wanderwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCexbjtChbL3_KM1RtY0POQMQYZtXFHKaA',
    appId: '1:627877852836:ios:49ab7132a55168c1809831',
    messagingSenderId: '627877852836',
    projectId: 'wanderwave-faf5a',
    storageBucket: 'wanderwave-faf5a.appspot.com',
    iosBundleId: 'com.example.wanderwave.RunnerTests',
  );
}
